apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler-task
  template:
    metadata:
      labels:
        app: crawler-task
    spec:
      containers:
      - name: crawler-task
        image: spirittq/crawler-task:latest
        ports:
        - containerPort: 3000
        livenessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-task
spec:
  selector:
    app: crawler-task
  ports:
    - name: http
      port: 8080
      targetPort: 3000
      nodePort: 31000
  type: NodePort