version: "3.9"

services:
  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    env_file:
      - ./crawler/.env
    environment:
      - SERVER_DOMAIN=data_manager
    depends_on:
      data_manager:
        condition: service_healthy
  data_manager:
    container_name: data_manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health_check"]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: .
      dockerfile: ./data_manager/Dockerfile
    env_file:
      - ./data_manager/.env
    ports:
      - "3000:3000"
      - "50051:50051"
    expose:
      - "3000"
      - "50051"
